CommandClasses:
  COMMAND_CLASS_ALARM:
    1: true
    2: true
    3: true
  COMMAND_CLASS_APPLICATION_STATUS:
  COMMAND_CLASS_ASSOCIATION:
    1: true
    2: true
  COMMAND_CLASS_BASIC:
    1: true
    2: true
  COMMAND_CLASS_BATTERY:
  COMMAND_CLASS_CLOCK:
  COMMAND_CLASS_COLOR_CONTROL:
  COMMAND_CLASS_CONFIGURATION:
  COMMAND_CLASS_DOOR_LOCK:
  COMMAND_CLASS_DOOR_LOCK_LOGGING:
  COMMAND_CLASS_MANUFACTURER_SPECIFIC:
  COMMAND_CLASS_MULTILEVEL_SENSOR:
  COMMAND_CLASS_NO_OPERATION:
  COMMAND_CLASS_NODE_NAMING:
  COMMAND_CLASS_NOTIFICATION:
    3: true
    4: true
    5: true
  COMMAND_CLASS_SECURITY:
  COMMAND_CLASS_SENSOR_CONFIGURATION:
  COMMAND_CLASS_SENSOR_MULTILEVEL:
  COMMAND_CLASS_SWITCH_ALL:
  COMMAND_CLASS_SWITCH_BINARY:
  COMMAND_CLASS_SWITCH_COLOR:
  COMMAND_CLASS_SWITCH_MULTILEVEL:
  COMMAND_CLASS_SWITCH_TOGGLE_BINARY:
  COMMAND_CLASS_THERMOSTAT_FAN_MODE:
  COMMAND_CLASS_THERMOSTAT_FAN_STATE:
  COMMAND_CLASS_THERMOSTAT_MODE:
  COMMAND_CLASS_THERMOSTAT_OPERATING_STATE:
  COMMAND_CLASS_THERMOSTAT_SETPOINT:
  COMMAND_CLASS_TIME:
  COMMAND_CLASS_USER_CODE:
  COMMAND_CLASS_VERSION:
  COMMAND_CLASS_WAKE_UP:
